
final List<String> Jobs = [
"Physician",
"Nurse",
"Dentist",
];

final List<String> Spec = [
  "none",
  "Allergist/Immunologist",
  "Anesthesiologist",
  "Cardiologist",
  "Colon and Rectal Surgeon",
  "Critical Care",
  "Dermatologist",
  "Endocrinologist",
  "Emergency Medicine",
  "Family Physician",
  "Geriatric Medicine",
  "Hematologist",
  "Hospice and Palliative Medicine",
  "Infectious Disease",
  "Internist",
  "Medical Geneticist",
  "Nephrologist",
  "Neurologist",
  "Obstetrician",
  "Gynecologist",
  "Oncologist",
  "Ophthalmologist",
  "Osteopath",
  "Otolaryngologist",
  "Pathologist",
  "Pediatrician",
  "Physiatrist",
  "Plastic Surgeon",
  "Podiatrist",
  "Preventive Medicine",
  "Psychiatrist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Sleep Medicine",
  "Sports Medicine",
  "General Surgeon",
  "Urologist",
];
