# Generated by Django 4.2.14 on 2024-08-01 08:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area_of_pain',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('full body', 'full body'), ('upper body', 'upper body'), ('lower body', 'lower body'), ('head', 'head'), ('neck', 'neck'), ('nose', 'nose'), ('mouth', 'mouth'), ('eyes', 'eyes'), ('ears', 'ears'), ('forehead', 'forehead'), ('shoulder', 'shoulder'), ('chest', 'chest'), ('arm', 'arm'), ('forearm', 'forearm'), ('hand', 'hand'), ('elbow', 'elbow'), ('wrist', 'wrist'), ('upper back', 'upper back'), ('lower back', 'lower back'), ('abdomen', 'abdomen'), ('glutes', 'glutes'), ('hips', 'hips'), ('genitals', 'genitals'), ('fingers/toes', 'fingers/toes'), ('palm', 'palm'), ('thigh', 'thigh'), ('knee', 'knee'), ('calf', 'calf'), ('ankle', 'ankle'), ('foot', 'foot')], max_length=211),
        ),
    ]
