# Generated by Django 4.2.14 on 2024-07-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medperson',
            name='user_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
