# Generated by Django 4.2.14 on 2024-07-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_medperson_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_med',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
